import type { Plant } from "./types";

/**
 * Seed plant database.
 *
 * Spacing follows Mel Bartholomew's Square Foot Gardening convention
 * (1, 4, 9, or 16 plants per 1-ft cell; larger plants span multiple cells).
 *
 * Sources used to verify spacing, days-to-maturity, zones, companion / antagonist
 * relationships, and cultivar notes:
 *  - Mel Bartholomew, "All New Square Foot Gardening" (3rd ed., Cool Springs Press)
 *  - The Old Farmer's Almanac plant guides (almanac.com/plant)
 *  - Cornell Vegetable Growing Guides (gardening.cornell.edu/homegardening)
 *  - University of Minnesota Extension (extension.umn.edu/vegetables)
 *  - Oregon State Extension Master Gardener resources (extension.oregonstate.edu)
 *  - Royal Horticultural Society (rhs.org.uk) for ornamental & herb data
 *  - USDA Plant Hardiness Zone Map (2023 update)
 */
export const PLANTS: Plant[] = [
  {
    id: "tomato",
    name: "Tomato",
    category: "vegetable",
    emoji: "🍅",
    spacingIn: 24,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["acidic", "neutral"],
    zones: [3, 11],
    plantMonths: [4, 5, 6],
    harvestMonths: [7, 8, 9, 10],
    daysToMaturity: 75,
    companions: ["basil", "carrot", "marigold", "lettuce", "onion", "parsley"],
    antagonists: ["brassica", "fennel", "corn", "potato"],
    notes: "Stake or cage. Avoid planting near brassicas — they stunt each other.",
    shopSearch: "tomato plant",
    varieties: [
      { name: "Better Boy", description: "Classic large red slicer. Disease-resistant and reliable.", daysToMaturity: 75, form: "both" },
      { name: "Roma", description: "Meaty paste tomato — the go-to for sauce and salsa.", daysToMaturity: 75, form: "both" },
      { name: "Sun Gold", description: "Sweet, candy-like orange cherry tomato. Very productive.", daysToMaturity: 65, form: "both" },
      { name: "Cherokee Purple", description: "Rich, smoky heirloom with deep purple shoulders.", daysToMaturity: 80, form: "both" },
    ],
  },
  {
    id: "basil",
    name: "Basil",
    category: "herb",
    emoji: "🌿",
    spacingIn: 12,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [5, 6],
    harvestMonths: [6, 7, 8, 9],
    daysToMaturity: 60,
    companions: ["tomato", "pepper", "marigold"],
    antagonists: ["sage", "rue"],
    notes: "Classic tomato companion — repels hornworms and improves flavor.",
    shopSearch: "basil plant",
    varieties: [
      { name: "Genovese", description: "Large-leaf Italian basil — the pesto standard.", daysToMaturity: 60, form: "both" },
      { name: "Sweet Basil", description: "All-purpose culinary basil, easy from seed.", daysToMaturity: 60, form: "both" },
      { name: "Thai Basil", description: "Anise/licorice notes for stir-fry and pho.", daysToMaturity: 65, form: "both" },
    ],
  },
  {
    id: "carrot",
    name: "Carrot",
    category: "vegetable",
    emoji: "🥕",
    spacingIn: 3,
    sun: "full-sun",
    water: "medium",
    soil: ["sandy", "loam"],
    ph: ["neutral", "acidic"],
    zones: [3, 10],
    plantMonths: [3, 4, 5, 7, 8],
    harvestMonths: [6, 7, 8, 9, 10],
    daysToMaturity: 70,
    companions: ["tomato", "onion", "lettuce", "rosemary", "pea"],
    antagonists: ["dill", "fennel"],
    shopSearch: "carrot seeds",
    varieties: [
      { name: "Nantes", description: "Sweet, cylindrical, blunt tip. Great for raised beds.", daysToMaturity: 65, form: "seed" },
      { name: "Danvers 126", description: "Tough, productive, tolerates heavier soil.", daysToMaturity: 75, form: "seed" },
      { name: "Little Finger", description: "Mini baby carrot — perfect for shallow beds.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "lettuce",
    name: "Lettuce",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 8,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 9],
    plantMonths: [3, 4, 5, 8, 9],
    harvestMonths: [5, 6, 7, 9, 10],
    daysToMaturity: 55,
    companions: ["carrot", "radish", "strawberry", "cucumber"],
    antagonists: ["brassica"],
    shopSearch: "lettuce seeds",
    varieties: [
      { name: "Buttercrunch", description: "Crisp Bibb-type with buttery flavor. Heat-tolerant.", daysToMaturity: 55, form: "both" },
      { name: "Black Seeded Simpson", description: "Loose-leaf, quick from seed, classic cut-and-come-again.", daysToMaturity: 45, form: "seed" },
      { name: "Romaine (Parris Island)", description: "Upright, crunchy heads — the Caesar salad green.", daysToMaturity: 70, form: "both" },
    ],
  },
  {
    id: "onion",
    name: "Onion",
    category: "vegetable",
    emoji: "🧅",
    spacingIn: 4,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 100,
    companions: ["tomato", "carrot", "lettuce", "strawberry"],
    antagonists: ["pea", "bean"],
    shopSearch: "onion sets",
    varieties: [
      { name: "Walla Walla Sweet", description: "Mild, juicy sweet onion. Best in long-day zones.", daysToMaturity: 110, form: "start" },
      { name: "Texas Sweet (Granex)", description: "Famous Vidalia-type — short-day, for southern beds.", daysToMaturity: 100, form: "start" },
      { name: "Red Burgundy", description: "Mild red onion, beautiful in salads.", daysToMaturity: 100, form: "start" },
    ],
  },
  {
    id: "pepper",
    name: "Pepper",
    category: "vegetable",
    emoji: "🌶️",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9, 10],
    daysToMaturity: 80,
    companions: ["basil", "onion", "carrot", "tomato"],
    antagonists: ["fennel", "brassica"],
    shopSearch: "pepper plant",
    varieties: [
      { name: "California Wonder", description: "Classic blocky green-to-red bell pepper.", daysToMaturity: 75, form: "both" },
      { name: "Jalapeño M", description: "Reliable medium-heat jalapeño for salsa.", daysToMaturity: 75, form: "both" },
      { name: "Cayenne Long Slim", description: "Hot, prolific, easy to dry.", daysToMaturity: 75, form: "both" },
    ],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    category: "vegetable",
    emoji: "🥒",
    spacingIn: 18,
    sun: "full-sun",
    water: "high",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 60,
    companions: ["bean", "pea", "radish", "sunflower", "lettuce"],
    antagonists: ["potato", "sage"],
    shopSearch: "cucumber seeds",
    varieties: [
      { name: "Marketmore 76", description: "Reliable slicer, disease-resistant, productive.", daysToMaturity: 65, form: "both" },
      { name: "Straight Eight", description: "All-America selection slicer — a beginner favorite.", daysToMaturity: 60, form: "both" },
      { name: "Boston Pickling", description: "Crunchy small fruits for homemade pickles.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "bean",
    name: "Bush Bean",
    category: "vegetable",
    emoji: "🫘",
    spacingIn: 4,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [5, 6, 7],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 55,
    companions: ["corn", "cucumber", "carrot", "strawberry"],
    antagonists: ["onion", "garlic", "fennel"],
    notes: "Fixes nitrogen — great for feeding hungry neighbors.",
    shopSearch: "bush bean seeds",
    varieties: [
      { name: "Blue Lake 274", description: "The standard green snap bean. Crisp and tender.", daysToMaturity: 55, form: "seed" },
      { name: "Provider", description: "Cold-tolerant, plant earlier than most.", daysToMaturity: 50, form: "seed" },
      { name: "Contender", description: "Heat-tolerant, heavy yields. Good for the South.", daysToMaturity: 50, form: "seed" },
    ],
  },
  {
    id: "corn",
    name: "Corn",
    category: "vegetable",
    emoji: "🌽",
    spacingIn: 12,
    sun: "full-sun",
    water: "high",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [5, 6],
    harvestMonths: [8, 9],
    daysToMaturity: 85,
    companions: ["bean", "squash", "cucumber"],
    antagonists: ["tomato"],
    notes: "Part of the Three Sisters: corn + beans + squash.",
    shopSearch: "sweet corn seeds",
    varieties: [
      { name: "Silver Queen", description: "Sweet white kernels. A southern classic.", daysToMaturity: 90, form: "seed" },
      { name: "Honey Select", description: "Sugary-enhanced yellow corn, very sweet.", daysToMaturity: 80, form: "seed" },
      { name: "Peaches & Cream", description: "Bi-color sweet corn with great flavor.", daysToMaturity: 85, form: "seed" },
    ],
  },
  {
    id: "squash",
    name: "Squash",
    category: "vegetable",
    emoji: "🎃",
    spacingIn: 36,
    sun: "full-sun",
    water: "high",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [5, 6],
    harvestMonths: [8, 9, 10],
    daysToMaturity: 90,
    companions: ["corn", "bean", "marigold"],
    antagonists: ["potato"],
    shopSearch: "squash seeds",
    varieties: [
      { name: "Waltham Butternut", description: "Sweet, nutty winter squash. Stores for months.", daysToMaturity: 105, form: "seed" },
      { name: "Yellow Crookneck", description: "Classic summer squash — pick young and tender.", daysToMaturity: 50, form: "both" },
      { name: "Table Queen Acorn", description: "Sweet acorn squash perfect for baking.", daysToMaturity: 85, form: "seed" },
    ],
  },
  {
    id: "strawberry",
    name: "Strawberry",
    category: "fruit",
    emoji: "🍓",
    spacingIn: 12,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["acidic"],
    zones: [3, 10],
    plantMonths: [3, 4, 9],
    harvestMonths: [5, 6, 7],
    daysToMaturity: 110,
    companions: ["lettuce", "onion", "bean", "spinach"],
    antagonists: ["brassica"],
    shopSearch: "strawberry plants",
    varieties: [
      { name: "Albion", description: "Day-neutral — fruits all summer. Sweet and firm.", daysToMaturity: 110, form: "start" },
      { name: "Ozark Beauty", description: "Everbearing favorite. Two big flushes a year.", daysToMaturity: 110, form: "start" },
      { name: "Seascape", description: "Day-neutral, heat-tolerant, great in containers.", daysToMaturity: 110, form: "start" },
    ],
  },
  {
    id: "spinach",
    name: "Spinach",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 6,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 10],
    daysToMaturity: 45,
    companions: ["strawberry", "pea", "radish"],
    antagonists: [],
    shopSearch: "spinach seeds",
    varieties: [
      { name: "Bloomsdale Long Standing", description: "Crinkled, sweet, slow to bolt in heat.", daysToMaturity: 45, form: "seed" },
      { name: "Space", description: "Smooth-leaf hybrid, mildew resistant, fast.", daysToMaturity: 40, form: "seed" },
    ],
  },
  {
    id: "radish",
    name: "Radish",
    category: "vegetable",
    emoji: "🌰",
    spacingIn: 3,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [2, 10],
    plantMonths: [3, 4, 5, 8, 9],
    harvestMonths: [4, 5, 6, 9, 10],
    daysToMaturity: 25,
    companions: ["lettuce", "cucumber", "pea", "spinach"],
    antagonists: ["hyssop"],
    shopSearch: "radish seeds",
    varieties: [
      { name: "Cherry Belle", description: "Round, crisp, mild — ready in 22 days.", daysToMaturity: 22, form: "seed" },
      { name: "French Breakfast", description: "Long, pink-and-white, slightly milder.", daysToMaturity: 25, form: "seed" },
      { name: "Easter Egg", description: "Mix of purple, pink, red, and white roots.", daysToMaturity: 28, form: "seed" },
    ],
  },
  {
    id: "pea",
    name: "Pea",
    category: "vegetable",
    emoji: "🫛",
    spacingIn: 4,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4],
    harvestMonths: [5, 6],
    daysToMaturity: 65,
    companions: ["carrot", "cucumber", "radish", "spinach"],
    antagonists: ["onion", "garlic"],
    shopSearch: "pea seeds",
    varieties: [
      { name: "Sugar Snap", description: "Sweet edible-pod pea, eat raw or cooked.", daysToMaturity: 65, form: "seed" },
      { name: "Lincoln", description: "Sweet shelling pea, heat-tolerant.", daysToMaturity: 65, form: "seed" },
      { name: "Little Marvel", description: "Compact bush pea, perfect for raised beds.", daysToMaturity: 60, form: "seed" },
    ],
  },
  {
    id: "potato",
    name: "Potato",
    category: "vegetable",
    emoji: "🥔",
    spacingIn: 12,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["acidic"],
    zones: [3, 10],
    plantMonths: [3, 4, 5],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 90,
    companions: ["bean", "corn", "marigold", "horseradish"],
    antagonists: ["tomato", "cucumber", "squash"],
    shopSearch: "seed potatoes",
    varieties: [
      { name: "Yukon Gold", description: "Buttery yellow flesh — the all-purpose favorite.", daysToMaturity: 90, form: "seed" },
      { name: "Russet Burbank", description: "Classic baking potato. Long storage.", daysToMaturity: 110, form: "seed" },
      { name: "Red Pontiac", description: "Smooth red skin, white flesh, dependable.", daysToMaturity: 90, form: "seed" },
    ],
  },
  {
    id: "brassica",
    name: "Broccoli / Cabbage",
    category: "vegetable",
    emoji: "🥦",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral", "alkaline"],
    zones: [3, 10],
    plantMonths: [3, 4, 8],
    harvestMonths: [6, 7, 10, 11],
    daysToMaturity: 80,
    companions: ["onion", "dill", "rosemary", "potato"],
    antagonists: ["tomato", "strawberry", "pepper"],
    shopSearch: "broccoli plant",
    varieties: [
      { name: "Calabrese (Broccoli)", description: "Classic Italian broccoli, big main head plus side shoots.", daysToMaturity: 65, form: "both" },
      { name: "Premium Crop (Broccoli)", description: "All-America winner — uniform large heads.", daysToMaturity: 65, form: "both" },
      { name: "Early Jersey Wakefield (Cabbage)", description: "Heirloom pointed-head cabbage. Compact.", daysToMaturity: 75, form: "both" },
    ],
  },
  {
    id: "marigold",
    name: "Marigold",
    category: "flower",
    emoji: "🌼",
    spacingIn: 10,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [2, 11],
    plantMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9, 10],
    companions: ["tomato", "pepper", "squash", "potato", "basil"],
    antagonists: [],
    notes: "Pest deterrent — great border plant.",
    shopSearch: "marigold plant",
    varieties: [
      { name: "Crackerjack", description: "Tall African marigold — huge pompom blooms.", form: "both" },
      { name: "Bonanza", description: "Compact French marigold, perfect bed border.", form: "both" },
      { name: "Lemon Gem", description: "Tiny edible flowers with citrus flavor.", form: "seed" },
    ],
  },
  {
    id: "rosemary",
    name: "Rosemary",
    category: "herb",
    emoji: "🌿",
    spacingIn: 24,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral", "alkaline"],
    zones: [7, 10],
    plantMonths: [4, 5],
    harvestMonths: [5, 6, 7, 8, 9, 10],
    companions: ["carrot", "bean", "brassica"],
    antagonists: [],
    shopSearch: "rosemary plant",
    varieties: [
      { name: "Tuscan Blue", description: "Upright, strong-flavored — the chef's choice.", form: "start" },
      { name: "Arp", description: "Cold-hardy down to zone 6 with mulch.", form: "start" },
    ],
  },
  {
    id: "parsley",
    name: "Parsley",
    category: "herb",
    emoji: "🌱",
    spacingIn: 8,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 9],
    plantMonths: [3, 4, 5],
    harvestMonths: [6, 7, 8, 9],
    companions: ["tomato", "carrot", "pepper"],
    antagonists: [],
    shopSearch: "parsley plant",
    varieties: [
      { name: "Italian Flat-Leaf", description: "The cooking standard — robust flavor.", form: "both" },
      { name: "Triple Curled", description: "Frilly, classic garnish parsley.", form: "both" },
    ],
  },
  {
    id: "sunflower",
    name: "Sunflower",
    category: "flower",
    emoji: "🌻",
    spacingIn: 18,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral", "alkaline"],
    zones: [4, 9],
    plantMonths: [4, 5, 6],
    harvestMonths: [8, 9, 10],
    companions: ["cucumber", "corn"],
    antagonists: ["potato", "bean"],
    shopSearch: "sunflower seeds",
    varieties: [
      { name: "Mammoth Russian", description: "10+ ft tall with giant edible seed heads.", form: "seed" },
      { name: "Autumn Beauty", description: "Multi-color blooms in red, gold, and bronze.", form: "seed" },
      { name: "Lemon Queen", description: "Soft yellow, branching, bee favorite.", form: "seed" },
    ],
  },
  // --- Vegetables (expanded) -------------------------------------------------
  {
    id: "kale",
    name: "Kale",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral", "alkaline"],
    zones: [3, 9],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 10, 11],
    daysToMaturity: 60,
    companions: ["onion", "dill", "potato", "brassica"],
    antagonists: ["tomato", "strawberry", "pepper"],
    shopSearch: "kale plant",
    varieties: [
      { name: "Lacinato (Dinosaur)", description: "Dark blue-green, blistered Italian heirloom.", daysToMaturity: 60, form: "both" },
      { name: "Red Russian", description: "Tender, sweet, frilly purple-veined leaves.", daysToMaturity: 55, form: "both" },
      { name: "Vates Blue Curled", description: "Cold-hardy curly kale — classic.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "swiss-chard",
    name: "Swiss Chard",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 9,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 5, 8],
    harvestMonths: [6, 7, 8, 9, 10],
    daysToMaturity: 55,
    companions: ["carrot", "onion", "brassica", "bean"],
    antagonists: [],
    notes: "Cut-and-come-again — pick outer leaves all season.",
    shopSearch: "swiss chard seeds",
    varieties: [
      { name: "Bright Lights", description: "Rainbow stems — yellow, pink, orange, red.", daysToMaturity: 55, form: "both" },
      { name: "Fordhook Giant", description: "Heirloom with thick white stems, very productive.", daysToMaturity: 60, form: "seed" },
      { name: "Ruby Red (Rhubarb Chard)", description: "Deep red stems and rich flavor.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "arugula",
    name: "Arugula",
    category: "vegetable",
    emoji: "🌿",
    spacingIn: 4,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 9, 10],
    harvestMonths: [4, 5, 6, 10, 11],
    daysToMaturity: 40,
    companions: ["lettuce", "spinach", "carrot", "cucumber"],
    antagonists: [],
    shopSearch: "arugula seeds",
    varieties: [
      { name: "Astro", description: "Mild, fast-growing salad arugula.", daysToMaturity: 35, form: "seed" },
      { name: "Wild (Sylvetta)", description: "Slower, deeper-flavored, slow to bolt.", daysToMaturity: 50, form: "seed" },
    ],
  },
  {
    id: "kohlrabi",
    name: "Kohlrabi",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 9,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 8],
    harvestMonths: [5, 6, 10],
    daysToMaturity: 60,
    companions: ["onion", "beet", "brassica"],
    antagonists: ["tomato", "strawberry", "pepper"],
    shopSearch: "kohlrabi seeds",
    varieties: [
      { name: "Early White Vienna", description: "Crisp, mild, pale-green bulbs.", daysToMaturity: 55, form: "seed" },
      { name: "Purple Vienna", description: "Striking purple skin, white interior.", daysToMaturity: 60, form: "seed" },
    ],
  },
  {
    id: "beet",
    name: "Beet",
    category: "vegetable",
    emoji: "🟣",
    spacingIn: 4,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 8],
    harvestMonths: [6, 7, 10],
    daysToMaturity: 60,
    companions: ["onion", "lettuce", "brassica", "kohlrabi"],
    antagonists: ["bean"],
    shopSearch: "beet seeds",
    varieties: [
      { name: "Detroit Dark Red", description: "Classic sweet red beet — the standard.", daysToMaturity: 60, form: "seed" },
      { name: "Chioggia", description: "Italian heirloom with red-and-white candy-stripe interior.", daysToMaturity: 55, form: "seed" },
      { name: "Golden", description: "Sweet golden-yellow beet, doesn't bleed.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "turnip",
    name: "Turnip",
    category: "vegetable",
    emoji: "🌰",
    spacingIn: 4,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4, 8],
    harvestMonths: [6, 7, 10],
    daysToMaturity: 50,
    companions: ["pea", "onion"],
    antagonists: ["potato"],
    shopSearch: "turnip seeds",
    varieties: [
      { name: "Purple Top White Globe", description: "Classic large turnip with purple shoulders.", daysToMaturity: 55, form: "seed" },
      { name: "Tokyo Cross", description: "Quick salad turnip, eat raw at golf-ball size.", daysToMaturity: 35, form: "seed" },
    ],
  },
  {
    id: "garlic",
    name: "Garlic",
    category: "vegetable",
    emoji: "🧄",
    spacingIn: 6,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [10, 11],
    harvestMonths: [6, 7],
    daysToMaturity: 240,
    companions: ["tomato", "strawberry", "brassica", "carrot"],
    antagonists: ["bean", "pea"],
    notes: "Plant cloves in fall; harvest the following summer when tops yellow.",
    shopSearch: "seed garlic",
    varieties: [
      { name: "Music (Hardneck)", description: "Big cloves, robust flavor — best for cold winters.", form: "start" },
      { name: "California Early (Softneck)", description: "Mild, stores long, braidable. Good for warm zones.", form: "start" },
      { name: "Inchelium Red (Softneck)", description: "Mild, sweet softneck — great all-rounder.", form: "start" },
    ],
  },
  {
    id: "leek",
    name: "Leek",
    category: "vegetable",
    emoji: "🌿",
    spacingIn: 6,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4],
    harvestMonths: [9, 10, 11],
    daysToMaturity: 120,
    companions: ["carrot", "celery", "onion"],
    antagonists: ["bean", "pea"],
    shopSearch: "leek seeds",
    varieties: [
      { name: "American Flag", description: "Hardy, mild, classic American heirloom.", daysToMaturity: 130, form: "seed" },
      { name: "King Richard", description: "Earliest leek — slim, mild, fast.", daysToMaturity: 75, form: "seed" },
    ],
  },
  {
    id: "scallion",
    name: "Scallion",
    category: "vegetable",
    emoji: "🌿",
    spacingIn: 2,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 7, 10],
    daysToMaturity: 60,
    companions: ["carrot", "lettuce", "strawberry", "tomato"],
    antagonists: ["bean", "pea"],
    shopSearch: "scallion seeds",
    varieties: [
      { name: "Evergreen Hardy White", description: "Bunching scallion — plant once, harvest for years.", daysToMaturity: 65, form: "seed" },
      { name: "Tokyo Long White", description: "Long, slender, mild Asian-style scallion.", daysToMaturity: 60, form: "seed" },
    ],
  },
  {
    id: "celery",
    name: "Celery",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 8,
    sun: "part-sun",
    water: "high",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [4, 5],
    harvestMonths: [8, 9, 10],
    daysToMaturity: 110,
    companions: ["leek", "onion", "brassica", "tomato"],
    antagonists: ["corn", "potato"],
    shopSearch: "celery plant",
    varieties: [
      { name: "Tall Utah", description: "Crisp, dark green, the supermarket standard.", daysToMaturity: 110, form: "both" },
      { name: "Golden Self-Blanching", description: "Milder, tender heirloom celery.", daysToMaturity: 100, form: "seed" },
    ],
  },
  {
    id: "eggplant",
    name: "Eggplant",
    category: "vegetable",
    emoji: "🍆",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 80,
    companions: ["pepper", "bean", "marigold", "basil"],
    antagonists: ["fennel"],
    shopSearch: "eggplant plant",
    varieties: [
      { name: "Black Beauty", description: "Big classic glossy purple — the supermarket standard.", daysToMaturity: 80, form: "both" },
      { name: "Ichiban", description: "Long, slim Japanese type. Productive, tender skin.", daysToMaturity: 65, form: "both" },
      { name: "Rosa Bianca", description: "Italian heirloom — round, lavender-streaked, mild.", daysToMaturity: 80, form: "both" },
    ],
  },
  {
    id: "okra",
    name: "Okra",
    category: "vegetable",
    emoji: "🌶️",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [5, 11],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9, 10],
    daysToMaturity: 60,
    companions: ["pepper", "basil", "tomato"],
    antagonists: [],
    notes: "Loves heat — perfect for southern beds.",
    shopSearch: "okra seeds",
    varieties: [
      { name: "Clemson Spineless", description: "Heirloom standard — productive, no thorns.", daysToMaturity: 60, form: "seed" },
      { name: "Burgundy", description: "Deep red pods on red-stemmed plants. Beautiful.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "vegetable",
    emoji: "🍠",
    spacingIn: 12,
    sun: "full-sun",
    water: "medium",
    soil: ["sandy", "loam"],
    ph: ["acidic", "neutral"],
    zones: [6, 11],
    plantMonths: [5, 6],
    harvestMonths: [9, 10],
    daysToMaturity: 100,
    companions: ["bean", "marigold"],
    antagonists: ["squash"],
    shopSearch: "sweet potato slips",
    varieties: [
      { name: "Beauregard", description: "Most popular orange-flesh variety. Reliable.", daysToMaturity: 105, form: "start" },
      { name: "Georgia Jet", description: "Fastest variety — best for short-season gardens.", daysToMaturity: 90, form: "start" },
    ],
  },
  {
    id: "winter-squash",
    name: "Winter Squash",
    category: "vegetable",
    emoji: "🎃",
    spacingIn: 36,
    sun: "full-sun",
    water: "high",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [5, 6],
    harvestMonths: [9, 10],
    daysToMaturity: 100,
    companions: ["corn", "bean", "marigold", "nasturtium"],
    antagonists: ["potato"],
    shopSearch: "winter squash seeds",
    varieties: [
      { name: "Butternut", description: "Sweet, nutty, stores all winter.", daysToMaturity: 105, form: "seed" },
      { name: "Acorn", description: "Sweet personal-size squash, perfect for baking.", daysToMaturity: 85, form: "seed" },
      { name: "Spaghetti", description: "Strands of squash that look like pasta when baked.", daysToMaturity: 100, form: "seed" },
    ],
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "vegetable",
    emoji: "🥒",
    spacingIn: 24,
    sun: "full-sun",
    water: "high",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 55,
    companions: ["corn", "bean", "nasturtium", "marigold"],
    antagonists: ["potato"],
    shopSearch: "zucchini plant",
    varieties: [
      { name: "Black Beauty", description: "Classic dark-green zucchini — productive and reliable.", daysToMaturity: 50, form: "both" },
      { name: "Costata Romanesco", description: "Ribbed Italian heirloom with nutty flavor.", daysToMaturity: 55, form: "seed" },
      { name: "Eight Ball", description: "Round green zucchini — perfect for stuffing.", daysToMaturity: 45, form: "seed" },
    ],
  },
  {
    id: "bok-choy",
    name: "Bok Choy",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 6,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 10],
    daysToMaturity: 45,
    companions: ["onion", "celery", "brassica"],
    antagonists: ["tomato", "strawberry"],
    shopSearch: "bok choy seeds",
    varieties: [
      { name: "Joi Choi", description: "Slow-bolt full-size bok choy. Crisp stems.", daysToMaturity: 45, form: "seed" },
      { name: "Toy Choi", description: "Mini baby bok choy — quick and tender.", daysToMaturity: 30, form: "seed" },
    ],
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    category: "vegetable",
    emoji: "🥦",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral", "alkaline"],
    zones: [3, 9],
    plantMonths: [3, 4, 8],
    harvestMonths: [6, 7, 10, 11],
    daysToMaturity: 75,
    companions: ["onion", "celery", "dill"],
    antagonists: ["tomato", "strawberry", "pepper"],
    shopSearch: "cauliflower plant",
    varieties: [
      { name: "Snowball Y", description: "Classic white cauliflower, self-blanching.", daysToMaturity: 75, form: "both" },
      { name: "Cheddar", description: "Bright orange heads with extra vitamin A.", daysToMaturity: 75, form: "start" },
      { name: "Graffiti", description: "Stunning purple heads that hold color when cooked.", daysToMaturity: 80, form: "start" },
    ],
  },
  {
    id: "brussels-sprouts",
    name: "Brussels Sprouts",
    category: "vegetable",
    emoji: "🌱",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral", "alkaline"],
    zones: [3, 9],
    plantMonths: [4, 5, 7],
    harvestMonths: [10, 11, 12],
    daysToMaturity: 100,
    companions: ["onion", "dill", "thyme", "brassica"],
    antagonists: ["tomato", "strawberry"],
    notes: "Sweetest after the first frost.",
    shopSearch: "brussels sprouts plant",
    varieties: [
      { name: "Long Island Improved", description: "Reliable heirloom, dense sprouts, hardy.", daysToMaturity: 100, form: "both" },
      { name: "Diablo", description: "Smooth, uniform large sprouts. Holds well in field.", daysToMaturity: 110, form: "both" },
    ],
  },
  {
    id: "pole-bean",
    name: "Pole Bean",
    category: "vegetable",
    emoji: "🫛",
    spacingIn: 6,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 65,
    companions: ["corn", "cucumber", "carrot", "strawberry", "squash"],
    antagonists: ["onion", "garlic", "fennel"],
    notes: "Needs a trellis or pole. Classic Three Sisters partner with corn.",
    shopSearch: "pole bean seeds",
    varieties: [
      { name: "Kentucky Wonder", description: "The classic heirloom pole bean — productive and stringless.", daysToMaturity: 65, form: "seed" },
      { name: "Scarlet Runner", description: "Edible bean with showy red flowers — hummingbird magnet.", daysToMaturity: 70, form: "seed" },
    ],
  },
  // --- Fruit (expanded) ------------------------------------------------------
  {
    id: "blueberry",
    name: "Blueberry",
    category: "fruit",
    emoji: "🫐",
    spacingIn: 48,
    sun: "full-sun",
    water: "medium",
    soil: ["peaty", "sandy", "loam"],
    ph: ["acidic"],
    zones: [3, 9],
    plantMonths: [3, 4, 10],
    harvestMonths: [6, 7, 8],
    daysToMaturity: 730,
    companions: ["strawberry"],
    antagonists: [],
    notes: "Loves acidic soil (pH 4.5–5.5). Best in its own bed or corner.",
    shopSearch: "blueberry bush",
    varieties: [
      { name: "Bluecrop", description: "Workhorse northern highbush — big, sweet berries.", form: "start" },
      { name: "Powderblue (Rabbiteye)", description: "Heat-tolerant southern blueberry.", form: "start" },
      { name: "Pink Lemonade", description: "Pink berries that ripen on a beautiful shrub.", form: "start" },
    ],
  },
  {
    id: "raspberry",
    name: "Raspberry",
    category: "fruit",
    emoji: "🍇",
    spacingIn: 24,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["acidic", "neutral"],
    zones: [3, 9],
    plantMonths: [3, 4],
    harvestMonths: [6, 7, 8, 9],
    daysToMaturity: 365,
    companions: ["garlic", "marigold"],
    antagonists: ["potato", "tomato"],
    shopSearch: "raspberry plant",
    varieties: [
      { name: "Heritage", description: "Everbearing red raspberry — summer and fall crops.", form: "start" },
      { name: "Caroline", description: "Large, sweet everbearing red — disease-resistant.", form: "start" },
      { name: "Black Hawk", description: "Hardy black raspberry with rich flavor.", form: "start" },
    ],
  },
  // --- Herbs (expanded) ------------------------------------------------------
  {
    id: "cilantro",
    name: "Cilantro",
    category: "herb",
    emoji: "🌿",
    spacingIn: 6,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 11],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 9, 10],
    daysToMaturity: 50,
    companions: ["tomato", "pepper", "bean", "spinach"],
    antagonists: ["fennel"],
    notes: "Bolts in heat — sow every 3 weeks for continuous harvest.",
    shopSearch: "cilantro seeds",
    varieties: [
      { name: "Santo", description: "Slow-bolt cilantro — the standard for fresh leaves.", daysToMaturity: 50, form: "both" },
      { name: "Calypso", description: "Slowest to bolt — best for summer cilantro.", daysToMaturity: 55, form: "seed" },
    ],
  },
  {
    id: "dill",
    name: "Dill",
    category: "herb",
    emoji: "🌿",
    spacingIn: 9,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 11],
    plantMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    daysToMaturity: 55,
    companions: ["brassica", "cucumber", "onion", "lettuce"],
    antagonists: ["carrot", "tomato"],
    shopSearch: "dill seeds",
    varieties: [
      { name: "Bouquet", description: "Compact, productive, classic pickling dill.", daysToMaturity: 55, form: "seed" },
      { name: "Fernleaf", description: "Slow-bolt dwarf dill — perfect for raised beds.", daysToMaturity: 60, form: "seed" },
    ],
  },
  {
    id: "thyme",
    name: "Thyme",
    category: "herb",
    emoji: "🌿",
    spacingIn: 12,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral", "alkaline"],
    zones: [4, 9],
    plantMonths: [4, 5],
    harvestMonths: [5, 6, 7, 8, 9],
    companions: ["brassica", "tomato", "rosemary"],
    antagonists: [],
    shopSearch: "thyme plant",
    varieties: [
      { name: "English (Common)", description: "The all-purpose culinary thyme.", form: "start" },
      { name: "Lemon", description: "Bright citrus thyme — great with chicken & fish.", form: "start" },
    ],
  },
  {
    id: "oregano",
    name: "Oregano",
    category: "herb",
    emoji: "🌿",
    spacingIn: 12,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral", "alkaline"],
    zones: [4, 10],
    plantMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    companions: ["pepper", "tomato", "basil"],
    antagonists: [],
    shopSearch: "oregano plant",
    varieties: [
      { name: "Greek", description: "Strong, peppery — the pizza & pasta standard.", form: "start" },
      { name: "Italian", description: "Milder, sweeter oregano, great for sauces.", form: "start" },
    ],
  },
  {
    id: "mint",
    name: "Mint",
    category: "herb",
    emoji: "🌿",
    spacingIn: 12,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [4, 5],
    harvestMonths: [5, 6, 7, 8, 9, 10],
    companions: ["tomato", "brassica"],
    antagonists: ["parsley"],
    notes: "Spreads aggressively — plant in a buried pot or its own corner.",
    shopSearch: "mint plant",
    varieties: [
      { name: "Spearmint", description: "Classic culinary mint — mojitos, tabbouleh, tea.", form: "start" },
      { name: "Peppermint", description: "Stronger menthol flavor — best for tea.", form: "start" },
      { name: "Chocolate Mint", description: "Fun cocoa-scented variety.", form: "start" },
    ],
  },
  {
    id: "chives",
    name: "Chives",
    category: "herb",
    emoji: "🌿",
    spacingIn: 6,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4],
    harvestMonths: [5, 6, 7, 8, 9],
    companions: ["tomato", "carrot", "strawberry"],
    antagonists: ["bean", "pea"],
    shopSearch: "chives plant",
    varieties: [
      { name: "Common Chives", description: "Classic mild onion-flavored herb with edible purple flowers.", form: "start" },
      { name: "Garlic Chives", description: "Flat-leaf with a mild garlic flavor.", form: "start" },
    ],
  },
  {
    id: "sage",
    name: "Sage",
    category: "herb",
    emoji: "🌿",
    spacingIn: 18,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral", "alkaline"],
    zones: [4, 9],
    plantMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9, 10],
    companions: ["brassica", "rosemary", "carrot"],
    antagonists: ["cucumber", "basil"],
    shopSearch: "sage plant",
    varieties: [
      { name: "Garden Sage (Common)", description: "Soft gray-green leaves, classic culinary sage.", form: "start" },
      { name: "Berggarten", description: "Compact, bushy, very flavorful — chef favorite.", form: "start" },
    ],
  },
  // --- Flowers (expanded) ----------------------------------------------------
  {
    id: "nasturtium",
    name: "Nasturtium",
    category: "flower",
    emoji: "🌺",
    spacingIn: 10,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [2, 11],
    plantMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9],
    companions: ["squash", "cucumber", "brassica", "tomato"],
    antagonists: [],
    notes: "Edible flowers and leaves — peppery like watercress. Trap-crops aphids.",
    shopSearch: "nasturtium seeds",
    varieties: [
      { name: "Jewel Mix", description: "Bushy, colorful mix — red, orange, yellow.", form: "seed" },
      { name: "Empress of India", description: "Deep crimson blooms on blue-green leaves.", form: "seed" },
    ],
  },
  {
    id: "zinnia",
    name: "Zinnia",
    category: "flower",
    emoji: "🌸",
    spacingIn: 9,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9, 10],
    companions: ["tomato", "pepper", "cucumber"],
    antagonists: [],
    notes: "Butterfly and pollinator magnet — great cut flower.",
    shopSearch: "zinnia seeds",
    varieties: [
      { name: "Benary's Giant", description: "4-inch double blooms in vibrant colors — classic cut flower.", form: "seed" },
      { name: "Profusion Mix", description: "Compact, disease-resistant, blooms nonstop.", form: "both" },
    ],
  },
  {
    id: "cosmos",
    name: "Cosmos",
    category: "flower",
    emoji: "🌸",
    spacingIn: 12,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [2, 11],
    plantMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9, 10],
    companions: ["tomato", "pepper"],
    antagonists: [],
    shopSearch: "cosmos seeds",
    varieties: [
      { name: "Sensation Mix", description: "Tall, pink/white blooms — pollinator favorite.", form: "seed" },
      { name: "Bright Lights", description: "Sulphureus type — orange and gold daisy-like blooms.", form: "seed" },
    ],
  },
  {
    id: "calendula",
    name: "Calendula",
    category: "flower",
    emoji: "🌼",
    spacingIn: 10,
    sun: "full-sun",
    water: "low",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [2, 10],
    plantMonths: [3, 4, 9],
    harvestMonths: [5, 6, 7, 8, 9, 10],
    companions: ["tomato", "brassica", "carrot"],
    antagonists: [],
    notes: "Edible petals — sometimes called 'poor man's saffron'.",
    shopSearch: "calendula seeds",
    varieties: [
      { name: "Resina", description: "Sticky resin-rich heirloom — best for salves and tinctures.", form: "seed" },
      { name: "Pacific Beauty", description: "Tall mixed-color cutting variety.", form: "seed" },
    ],
  },
  // --- Vegetables (round 2) -------------------------------------------------
  {
    id: "collards",
    name: "Collards",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 7, 8],
    harvestMonths: [6, 7, 10, 11, 12],
    daysToMaturity: 70,
    companions: ["onion", "dill", "potato", "brassica"],
    antagonists: ["tomato", "strawberry", "pepper"],
    notes: "Cold-hardy southern staple — flavor improves after frost.",
    shopSearch: "collard greens seeds",
    varieties: [
      { name: "Georgia Southern", description: "Classic heirloom — large blue-green leaves, slow to bolt.", daysToMaturity: 75, form: "seed" },
      { name: "Champion", description: "Compact, slow-bolting improvement on Vates.", daysToMaturity: 60, form: "both" },
    ],
  },
  {
    id: "mustard-greens",
    name: "Mustard Greens",
    category: "vegetable",
    emoji: "🥬",
    spacingIn: 6,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 10, 11],
    daysToMaturity: 40,
    companions: ["pea", "bean", "brassica"],
    antagonists: ["tomato"],
    shopSearch: "mustard greens seeds",
    varieties: [
      { name: "Florida Broadleaf", description: "Big, mild Southern mustard — quick salad or braising green.", daysToMaturity: 45, form: "seed" },
      { name: "Red Giant", description: "Striking purple-red leaves with a wasabi-like kick.", daysToMaturity: 45, form: "seed" },
    ],
  },
  {
    id: "shallot",
    name: "Shallot",
    category: "vegetable",
    emoji: "🧅",
    spacingIn: 4,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 10],
    harvestMonths: [7, 8],
    daysToMaturity: 100,
    companions: ["carrot", "lettuce", "strawberry", "tomato"],
    antagonists: ["bean", "pea"],
    notes: "Plant individual sets; each one multiplies into a cluster.",
    shopSearch: "shallot sets",
    varieties: [
      { name: "French Red", description: "Classic copper-red shallot, rich gourmet flavor.", form: "start" },
      { name: "Dutch Yellow", description: "Mild, easy-to-grow yellow shallot — stores well.", form: "start" },
    ],
  },
  {
    id: "parsnip",
    name: "Parsnip",
    category: "vegetable",
    emoji: "🥕",
    spacingIn: 6,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [4, 5],
    harvestMonths: [10, 11, 12],
    daysToMaturity: 120,
    companions: ["onion", "radish"],
    antagonists: ["carrot", "celery"],
    notes: "Sweetest after a hard frost — leave in the ground until needed.",
    shopSearch: "parsnip seeds",
    varieties: [
      { name: "Hollow Crown", description: "Long, tapered heirloom — sweet, classic flavor.", daysToMaturity: 130, form: "seed" },
      { name: "Gladiator F1", description: "Uniform, smooth-skinned hybrid with strong yields.", daysToMaturity: 110, form: "seed" },
    ],
  },
  {
    id: "tomatillo",
    name: "Tomatillo",
    category: "vegetable",
    emoji: "🍅",
    spacingIn: 24,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    daysToMaturity: 75,
    companions: ["basil", "pepper", "marigold", "cilantro"],
    antagonists: ["brassica", "fennel"],
    notes: "Plant at least two — tomatillos need cross-pollination to set fruit.",
    shopSearch: "tomatillo plant",
    varieties: [
      { name: "Toma Verde", description: "Classic green tomatillo — bright, tart salsa verde standard.", daysToMaturity: 70, form: "both" },
      { name: "Purple", description: "Sweeter purple-husked variety — good for fresh salsa.", daysToMaturity: 75, form: "both" },
    ],
  },
  {
    id: "cantaloupe",
    name: "Cantaloupe",
    category: "vegetable",
    emoji: "🍈",
    spacingIn: 36,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [8, 9],
    daysToMaturity: 85,
    companions: ["corn", "bean", "nasturtium", "radish"],
    antagonists: ["potato"],
    notes: "Vining — trellis or give it space. Ripe when stem slips off easily.",
    shopSearch: "cantaloupe seeds",
    varieties: [
      { name: "Hale's Best", description: "Classic orange-flesh muskmelon, sweet and aromatic.", daysToMaturity: 85, form: "both" },
      { name: "Minnesota Midget", description: "Compact short-season variety, great for raised beds.", daysToMaturity: 65, form: "seed" },
    ],
  },
  {
    id: "watermelon",
    name: "Watermelon",
    category: "vegetable",
    emoji: "🍉",
    spacingIn: 36,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [4, 11],
    plantMonths: [5, 6],
    harvestMonths: [8, 9],
    daysToMaturity: 90,
    companions: ["corn", "bean", "nasturtium", "radish"],
    antagonists: ["potato"],
    notes: "Heat lover — pick when the tendril nearest the fruit dries up.",
    shopSearch: "watermelon seeds",
    varieties: [
      { name: "Sugar Baby", description: "Compact icebox melon — 8-10 lb, perfect for small beds.", daysToMaturity: 75, form: "seed" },
      { name: "Crimson Sweet", description: "Classic big striped picnic watermelon — sweet & juicy.", daysToMaturity: 85, form: "both" },
    ],
  },
  {
    id: "edamame",
    name: "Edamame",
    category: "vegetable",
    emoji: "🫛",
    spacingIn: 6,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [5, 6],
    harvestMonths: [8, 9],
    daysToMaturity: 90,
    companions: ["corn", "cucumber", "strawberry"],
    antagonists: ["onion", "garlic"],
    notes: "Bushy soybean — fixes nitrogen. Pick whole pods when plump & green.",
    shopSearch: "edamame seeds",
    varieties: [
      { name: "Midori Giant", description: "Large, sweet pods — the most popular home garden edamame.", daysToMaturity: 85, form: "seed" },
      { name: "Envy", description: "Short-season early variety — good for northern gardens.", daysToMaturity: 75, form: "seed" },
    ],
  },
  {
    id: "asparagus",
    name: "Asparagus",
    category: "vegetable",
    emoji: "🌱",
    spacingIn: 18,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 8],
    plantMonths: [3, 4],
    harvestMonths: [4, 5, 6],
    daysToMaturity: 730,
    companions: ["tomato", "parsley", "basil"],
    antagonists: ["onion", "garlic", "potato"],
    notes: "Perennial — plant once, harvest spears for 20+ years. Skip year-1 harvest.",
    shopSearch: "asparagus crowns",
    varieties: [
      { name: "Jersey Knight", description: "All-male hybrid — high-yielding and disease-resistant.", form: "start" },
      { name: "Purple Passion", description: "Sweet, tender purple spears that turn green when cooked.", form: "start" },
    ],
  },
  {
    id: "rhubarb",
    name: "Rhubarb",
    category: "vegetable",
    emoji: "🌿",
    spacingIn: 36,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["acidic", "neutral"],
    zones: [3, 8],
    plantMonths: [3, 4, 10],
    harvestMonths: [4, 5, 6, 7],
    daysToMaturity: 365,
    companions: ["brassica", "strawberry"],
    antagonists: [],
    notes: "Perennial — eat the stalks only. Leaves are toxic. Wait until year 2 to harvest.",
    shopSearch: "rhubarb crowns",
    varieties: [
      { name: "Victoria", description: "Classic green-and-red stalks, mild and reliable.", form: "start" },
      { name: "Canada Red", description: "Deep red stalks, sweeter than most — great for pies.", form: "start" },
    ],
  },
  // --- Fruit (round 2) ------------------------------------------------------
  {
    id: "blackberry",
    name: "Blackberry",
    category: "fruit",
    emoji: "🫐",
    spacingIn: 36,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["acidic", "neutral"],
    zones: [5, 10],
    plantMonths: [3, 4],
    harvestMonths: [6, 7, 8],
    daysToMaturity: 365,
    companions: ["garlic"],
    antagonists: ["raspberry", "strawberry"],
    notes: "Trellis thornless varieties on a fence — much easier to pick.",
    shopSearch: "blackberry plant",
    varieties: [
      { name: "Triple Crown", description: "Thornless, huge berries, very productive semi-erect canes.", form: "start" },
      { name: "Navaho", description: "Thornless, upright, excellent flavor — patio-friendly.", form: "start" },
    ],
  },
  {
    id: "currant",
    name: "Currant",
    category: "fruit",
    emoji: "🍇",
    spacingIn: 48,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 8],
    plantMonths: [3, 4, 10],
    harvestMonths: [6, 7],
    daysToMaturity: 730,
    companions: ["gooseberry"],
    antagonists: [],
    notes: "Tolerates part shade — great for cooler corners. Tart fresh, perfect for jam.",
    shopSearch: "currant bush",
    varieties: [
      { name: "Red Lake", description: "Reliable, productive red currant — the classic for jelly.", form: "start" },
      { name: "Ben Sarek", description: "Compact black currant — high vitamin C, rich flavor.", form: "start" },
    ],
  },
  {
    id: "gooseberry",
    name: "Gooseberry",
    category: "fruit",
    emoji: "🫐",
    spacingIn: 48,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [3, 8],
    plantMonths: [3, 4, 10],
    harvestMonths: [6, 7],
    daysToMaturity: 730,
    companions: ["currant"],
    antagonists: [],
    shopSearch: "gooseberry bush",
    varieties: [
      { name: "Hinnonmaki Red", description: "Sweet-tart red dessert gooseberry — eat fresh.", form: "start" },
      { name: "Invicta", description: "Heavy-cropping green, mildew-resistant.", form: "start" },
    ],
  },
  {
    id: "grape",
    name: "Grape",
    category: "fruit",
    emoji: "🍇",
    spacingIn: 72,
    sun: "full-sun",
    water: "medium",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [3, 4],
    harvestMonths: [8, 9, 10],
    daysToMaturity: 1095,
    companions: ["basil", "hyssop"],
    antagonists: ["cabbage"],
    notes: "Needs a sturdy trellis or arbor. First crop in year 3.",
    shopSearch: "grape vine",
    varieties: [
      { name: "Concord", description: "Classic American blue grape — juice, jelly, eating.", form: "start" },
      { name: "Reliance", description: "Cold-hardy seedless pink table grape.", form: "start" },
      { name: "Thompson Seedless", description: "Sweet green seedless — best in long, hot summers.", form: "start" },
    ],
  },
  // --- Herbs (round 2) ------------------------------------------------------
  {
    id: "lavender",
    name: "Lavender",
    category: "herb",
    emoji: "💜",
    spacingIn: 18,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral", "alkaline"],
    zones: [5, 9],
    plantMonths: [4, 5],
    harvestMonths: [6, 7, 8],
    companions: ["rosemary", "thyme", "sage", "oregano"],
    antagonists: [],
    notes: "Loves dry feet — perfect for raised beds. Cut for drying just as buds open.",
    shopSearch: "lavender plant",
    varieties: [
      { name: "Munstead", description: "Compact English lavender — hardy, fragrant, classic.", form: "start" },
      { name: "Hidcote", description: "Deep-purple English lavender, excellent for borders.", form: "start" },
      { name: "Phenomenal", description: "Hybrid — heat- and humidity-tolerant for the South.", form: "start" },
    ],
  },
  {
    id: "tarragon",
    name: "Tarragon",
    category: "herb",
    emoji: "🌿",
    spacingIn: 18,
    sun: "full-sun",
    water: "low",
    soil: ["sandy", "loam"],
    ph: ["neutral"],
    zones: [4, 9],
    plantMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    companions: ["tomato", "eggplant"],
    antagonists: [],
    notes: "Always buy French tarragon as a plant — Russian tarragon is flavorless.",
    shopSearch: "french tarragon plant",
    varieties: [
      { name: "French", description: "True culinary tarragon — anise/licorice flavor, propagated by division.", form: "start" },
    ],
  },
  {
    id: "fennel",
    name: "Fennel",
    category: "herb",
    emoji: "🌿",
    spacingIn: 12,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 9],
    plantMonths: [4, 5, 7, 8],
    harvestMonths: [7, 8, 9, 10],
    daysToMaturity: 80,
    companions: [],
    antagonists: ["tomato", "bean", "pepper", "cilantro", "dill"],
    notes: "Allelopathic — most plants dislike it. Give it its own corner.",
    shopSearch: "fennel seeds",
    varieties: [
      { name: "Florence (Finocchio)", description: "Bulbing fennel — sweet aniseed bulbs for roasting & salads.", daysToMaturity: 80, form: "seed" },
      { name: "Bronze", description: "Ornamental bronze-leaf fennel — feathery foliage, edible seeds.", form: "seed" },
    ],
  },
  {
    id: "lemon-balm",
    name: "Lemon Balm",
    category: "herb",
    emoji: "🌿",
    spacingIn: 18,
    sun: "part-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 9],
    plantMonths: [4, 5],
    harvestMonths: [5, 6, 7, 8, 9],
    companions: ["tomato", "squash", "melon"],
    antagonists: [],
    notes: "Self-seeds aggressively — deadhead before flowering or contain like mint.",
    shopSearch: "lemon balm plant",
    varieties: [
      { name: "Common", description: "Bright lemon-scented mint relative — tea, salads, dessert.", form: "start" },
      { name: "Aurea", description: "Variegated gold-and-green leaves — ornamental and useful.", form: "start" },
    ],
  },
  {
    id: "chamomile",
    name: "Chamomile",
    category: "herb",
    emoji: "🌼",
    spacingIn: 6,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 9],
    plantMonths: [3, 4, 5],
    harvestMonths: [6, 7, 8],
    daysToMaturity: 70,
    companions: ["brassica", "onion", "cucumber"],
    antagonists: [],
    notes: "Apple-scented flowers for tea. German type is annual; Roman is a perennial groundcover.",
    shopSearch: "chamomile seeds",
    varieties: [
      { name: "German", description: "Tall annual — the classic tea chamomile.", daysToMaturity: 65, form: "seed" },
      { name: "Roman", description: "Low-growing perennial — apple-scented lawn alternative.", form: "start" },
    ],
  },
  // --- Flowers (round 2) ----------------------------------------------------
  {
    id: "borage",
    name: "Borage",
    category: "flower",
    emoji: "💙",
    spacingIn: 18,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [2, 11],
    plantMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9],
    companions: ["tomato", "squash", "strawberry", "cucumber"],
    antagonists: [],
    notes: "Bee magnet with edible cucumber-flavored star flowers. Self-seeds freely.",
    shopSearch: "borage seeds",
    varieties: [
      { name: "Common Blue", description: "Classic sky-blue star flowers — pollinator favorite.", form: "seed" },
      { name: "Alba", description: "White-flowered borage — same culinary uses, prettier in salads.", form: "seed" },
    ],
  },
  {
    id: "bachelors-button",
    name: "Bachelor's Button",
    category: "flower",
    emoji: "🌸",
    spacingIn: 6,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral", "alkaline"],
    zones: [2, 11],
    plantMonths: [3, 4, 9],
    harvestMonths: [5, 6, 7, 8],
    companions: ["tomato", "squash"],
    antagonists: [],
    notes: "Also called cornflower. Edible blue petals brighten salads.",
    shopSearch: "bachelor button seeds",
    varieties: [
      { name: "Blue Boy", description: "Classic true-blue cornflower — heirloom standard.", form: "seed" },
      { name: "Polka Dot Mix", description: "Dwarf compact mix in blue, pink, white, maroon.", form: "seed" },
    ],
  },
  {
    id: "snapdragon",
    name: "Snapdragon",
    category: "flower",
    emoji: "🌷",
    spacingIn: 8,
    sun: "full-sun",
    water: "medium",
    soil: ["loam"],
    ph: ["neutral"],
    zones: [4, 10],
    plantMonths: [3, 4, 5],
    harvestMonths: [5, 6, 7, 8, 9, 10],
    companions: ["tomato", "pepper"],
    antagonists: [],
    notes: "Cool-season bloomer — plants out before last frost. Pinch tips for bushier growth.",
    shopSearch: "snapdragon plant",
    varieties: [
      { name: "Rocket Mix", description: "Tall 3-ft cut-flower snapdragons — classic florist variety.", form: "both" },
      { name: "Madame Butterfly", description: "Double-azalea-form blooms in a wide color mix.", form: "seed" },
    ],
  },
  {
    id: "sweet-alyssum",
    name: "Sweet Alyssum",
    category: "flower",
    emoji: "🤍",
    spacingIn: 4,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 10],
    plantMonths: [3, 4, 9],
    harvestMonths: [4, 5, 6, 7, 8, 9, 10],
    companions: ["brassica", "lettuce", "tomato", "carrot"],
    antagonists: [],
    notes: "Honey-scented carpet that attracts hoverflies — natural aphid control.",
    shopSearch: "sweet alyssum seeds",
    varieties: [
      { name: "Carpet of Snow", description: "Classic low white carpet — fragrant and reliable.", form: "both" },
      { name: "Easter Bonnet Mix", description: "Compact mix of white, pink, and lavender flowers.", form: "both" },
    ],
  },
  // --- Cover crops ----------------------------------------------------------
  {
    id: "crimson-clover",
    name: "Crimson Clover",
    category: "cover-crop",
    emoji: "🌱",
    spacingIn: 4,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [3, 11],
    plantMonths: [3, 4, 8, 9],
    harvestMonths: [],
    companions: [],
    antagonists: [],
    notes: "Nitrogen-fixing legume cover crop. Showy crimson blooms feed pollinators; mow before seed set.",
    shopSearch: "crimson clover seed",
    varieties: [
      { name: "Dixie", description: "Most widely-grown reseeding crimson clover for the South.", form: "seed" },
      { name: "AU Robin", description: "Early-maturing crimson clover bred for cold tolerance.", form: "seed" },
    ],
  },
  {
    id: "buckwheat",
    name: "Buckwheat",
    category: "cover-crop",
    emoji: "🌾",
    spacingIn: 3,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy", "clay"],
    ph: ["acidic", "neutral"],
    zones: [3, 11],
    plantMonths: [5, 6, 7],
    harvestMonths: [],
    daysToMaturity: 40,
    companions: [],
    antagonists: [],
    notes: "Fastest summer cover — flowers in 4 weeks, suppresses weeds, mines phosphorus.",
    shopSearch: "buckwheat seed",
    varieties: [
      { name: "Common", description: "Standard summer smother crop — turn under at flowering.", form: "seed" },
    ],
  },
  {
    id: "winter-rye",
    name: "Winter Rye",
    category: "cover-crop",
    emoji: "🌾",
    spacingIn: 2,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy", "clay"],
    ph: ["acidic", "neutral"],
    zones: [3, 9],
    plantMonths: [9, 10, 11],
    harvestMonths: [],
    companions: [],
    antagonists: [],
    notes: "Hardiest winter cereal cover — survives -30°F. Cut before heading, then turn under.",
    shopSearch: "winter rye seed",
    varieties: [
      { name: "Aroostook", description: "Cold-hardy New England winter rye, strong fall growth.", form: "seed" },
      { name: "Wheeler", description: "Productive winter rye widely sold for cover-crop use.", form: "seed" },
    ],
  },
  {
    id: "hairy-vetch",
    name: "Hairy Vetch",
    category: "cover-crop",
    emoji: "🌱",
    spacingIn: 4,
    sun: "full-sun",
    water: "low",
    soil: ["loam", "sandy"],
    ph: ["neutral"],
    zones: [4, 8],
    plantMonths: [8, 9, 10],
    harvestMonths: [],
    companions: [],
    antagonists: [],
    notes: "Top winter N-fixer — pairs well overseeded with winter rye. Mow at flowering.",
    shopSearch: "hairy vetch seed",
    varieties: [
      { name: "Common", description: "Standard winter-hardy hairy vetch for cover cropping.", form: "seed" },
      { name: "Purple Bounty", description: "Earlier-flowering selection, USDA-bred for the Mid-Atlantic.", form: "seed" },
    ],
  },
];

export const PLANT_BY_ID = new Map(PLANTS.map((p) => [p.id, p] as const));

export function getPlant(id: string) {
  return PLANT_BY_ID.get(id);
}
